### ISSUE TITLE
Given a monolithic RADON model, the DECOMP_TOOL should be able to generate a coarse-grained RADON model

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#1]
| ID | R-T3.2-1 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to decompose the architecture of a monolithic application based on microservices. |
| Requirement | Given a monolithic RADON model, the DECOMP_TOOL should be able to generate a coarse-grained RADON model. |
| Extended Description | A RADON application or model may be said to be monolithic, coarse-grained or fine-grained depending on whether it consists of a monolith, microservices or serverless functions with separate storages. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
Coase-grained decomposition has been supported by the decomposition tool.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
