### ISSUE TITLE
The DECOMP_TOOL should be able to allow the option of specifying the solution method for deployment optimization and obtain the optimal deployment scheme with that method

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#10]
From D2.1 (Companion)
| ID | R-T3.2-10 |
| --- | --- | 
| Type | USABILITY |
| User Story | As an Operations Engineer, I want to optimize the deployment of an application with different solution methods. |
| Requirement | The DECOMP_TOOL should be able to allow the option of specifying the solution method for deployment optimization and obtain the optimal deployment scheme with that method. |
| Extended Description | The available methods may include cutting planes, branch & bound and generic heuristics. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
Deployment optimization for a RADON model is typically a non-linear mixed-integer programming problem. At present, generic algorithms are the only method that can handle this kind of problem well. This feature is reserved for now.

**Comment by zhululai** [comment]
Deployment optimization for a RADON model is typically a non-linear mixed-integer programming problem. At present, generic algorithms are the only method that is suitable to solve this kind of problem. This feature is reserved for now.

**Comment by zhululai** [comment]
Deployment optimization for a RADON model is typically a non-linear mixed-integer programming problem. At present, genetic algorithms are the only method that is suitable to solve this kind of problem. This feature is reserved for now.

**Comment by zhululai** [comment]
Deployment optimization for a RADON model is typically a non-linear mixed-integer programming problem. At present, genetic algorithms are the only solution method that is suitable for this kind of problem. This feature is reserved for now.

**Comment by zhululai** [comment]
@gcasale update requirement (see #13).

**Comment by gcasale** [comment]
Accepted
