### ISSUE TITLE
Minor installation glitches

### ISSUE THREAD

**Issue by gcasale** [radon-h2020/radon-decomposition-tool#12]
The demo worked smoothly but some minor issues with the getting started instructions.

State in README.md in which folder one should start this command:

 curl -X POST http://ec2-108-128-104-167.eu-west-1.compute.amazonaws.com:9000/files/model.yml -F 'file=@open_model.yml'

This command overwrites the example model, use a different name for the output or one needs to check out again to check what has changed:

curl -X GET http://ec2-108-128-104-167.eu-west-1.compute.amazonaws.com:9000/files/model.yml -o open_model.yml

It would be best to indicate what has changed directly in the README.md

**Comment by gcasale** [comment]
@zhululai Please confirm status of this open issue

**Comment by zhululai** [comment]
@gcasale This issue has been fixed
