### ISSUE TITLE
The DECOMP_TOOL should be able to allow the option of specifying the solution method for deployment optimization and obtain the optimal deployment scheme with that method

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#13]
From D2.1 (Companion)
| ID | R-T3.2-10 |
| --- | --- | 
| Type | USABILITY |
| User Story | As an Operations Engineer, I want to optimize the deployment of an application with different solution methods. |
| Requirement | The DECOMP_TOOL should be able to allow the option of specifying the solution method for deployment optimization and obtain the optimal deployment scheme with that method. |
| Extended Description | The available methods may include genetic algorithms and other suitable ones. |
| Priority | Could have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Approved

**Comment by zhululai** [comment]
Deployment optimization with a genetic algorithm has been supported by the decomposition tool. Since this algorithm is the only solution method found applicable, specification of other solution methods is not allowed at present.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
