### ISSUE TITLE
The DECOMP_TOOL should be able to access a database containing microservices traces and extract the relevant information in order to provide estimates of the demand. 

### ISSUE THREAD

**Issue by JosePerusquia** [radon-h2020/radon-decomposition-tool#14]
| ID | R-T3.2-12|
| --- | --- |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to enhance the accuracy performance prediction of the demand estimation.|
| Requirement | The DECOMP_TOOL should be able to access a database containing microservices traces and extract the relevant information in order to provide estimates of the demand. |
| Extended Description | Demand estimation is an important task in order to fully characterise the network model used. The DECOMP_TOOL uses layered queueing network models which require an estimate of the demand for every class of process.|
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Requirement approved.

**Comment by gcasale** [comment]
Met using files rather than database
