### ISSUE TITLE
The DECOMP_TOOL should be able to account for response time distribution in a RADON model

### ISSUE THREAD

**Issue by ZifengNiu** [radon-h2020/radon-decomposition-tool#15]
| ID | R-T3.2-13 |
| --- | --- |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to estimate the variability of unknown response time, such as the percentile information of its distribution. |
| Requirement | Given a RADON model, the DECOMP_TOOL can take into account response time distribution upon solving the optimisation model. |
| Extended Description | The response time can be described in terms of percentiles and the first three moments of the distribution. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Requirement approved.

**Comment by gcasale** [comment]
Completed
