### ISSUE TITLE
The DECOMP_TOOL should be able to optimize the collocation of microservices

### ISSUE THREAD

**Issue by lefteran** [radon-h2020/radon-decomposition-tool#16]
| ID | R-T3.2-14|
| --- | --- |
| Type | OPTIMIZATION FEATURE|
| User Story | As a Software Designer, I want to design algorithms for the optimization of the performance. |
| Requirement | Given a RADON model, the DECOMP_TOOL should be able to optimize the collocation of microservices taking into account interference data. |
| Extended Description | The idea is to reduce the cost and energy consumption given budget constraints.|
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Completed
