### ISSUE TITLE
The DECOMP_TOOL should be able to train a machine learning model to predict the interference between the collocated microservices

### ISSUE THREAD

**Issue by Aalnafessah** [radon-h2020/radon-decomposition-tool#17]
| ID | R-T3.2-15 |
| --- | --- |
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Developer, I want to learn the interference between microservices that I will be designed and implemented when they are collocated. |
| Requirement | The DECOMP_TOOL should be able to train a machine learning model to predict the interference between the collocated microservices|
| Extended Description | An AI-driven model is implemented to predict the services' interference, which may cause low system utilization or saturated system resources. This feature will alleviate and estimate the task slowdown affected by the interference among running services.|
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests, and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Completed
