### ISSUE TITLE
Given a coarse-grained RADON model, the DECOMP_TOOL should be able to generate a fine-grained RADON model

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#2]
From D2.1 (Companion)
| ID | R-T3.2-2 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to decompose the architecture of a coarse-grained application based on serverless functions. |
| Requirement | Given a coarse-grained RADON model, the DECOMP_TOOL should be able to generate a fine-grained RADON model. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
Fine-grained decomposition has been supported by the decomposition tool.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
