### ISSUE TITLE
Given a platform-independent RADON model, the DECOMP_TOOL must be able to obtain an optimal deployment scheme that minimizes the operating costs on a specific cloud platform under the performance requirements

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#3]
From D2.1 (Companion)
| ID | R-T3.2-3 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As an Operations Engineer, I want to optimize the deployment of an application on any cloud platform. |
| Requirement | Given a platform-independent RADON model, the DECOMP_TOOL must be able to obtain an optimal deployment scheme that minimizes the operating costs on a specific cloud platform under the performance requirements. |
| Extended Description | A platform-independent RADON model comprises nodes and relationships that are agnostic of any cloud platform. |
| Priority | Must have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
The optimization procedure essentially requires the given model to include a benchmark on a specific cloud platform. Therefore, the DECOMP_TOOL cannot deal with a platform-independent model, where all the nodes and relationships are agnostic of any cloud platform.

**Comment by zhululai** [comment]
The optimization procedure essentially requires the given model to be benchmarked on a specific cloud platform. Therefore, the DECOMP_TOOL cannot deal with a platform-independent model, where all the nodes and relationships are agnostic of any cloud platform.

**Comment by zhululai** [comment]
@gcasale remove requirement.

**Comment by zhululai** [comment]
The optimization procedure essentially requires the given model to be benchmarked on a specific cloud platform. Therefore, the DECOMP_TOOL cannot deal with a platform-independent model, where all the nodes and relationships are agnostic of any cloud platform. This feature is not supported.

**Comment by zhululai** [comment]
The optimization procedure essentially requires creating a benchmark on a specific cloud platform. Therefore, the decomposition tool cannot deal with a platform-independent RADON model. This feature is not supported.

**Comment by zhululai** [comment]
@gcasale remove requirement.

**Comment by gcasale** [comment]
Change rejected - one can still indicate assumed demands without benchmarking and the tool will continue to work. Please keep this requirement.

**Comment by zhululai** [comment]
The TOSCA definitions currrently allow the specification of demands in abstract nodes. However, the decomposition tool cannot instantiate a layered queueing network barely with demands. The scheduling and multiplicity of the tasks may vary across different cloud platforms, e.g. AWS vs Azure.

**Comment by zhululai** [comment]
@gcasale please reconsider.

**Comment by gcasale** [comment]
OK, approved
