### ISSUE TITLE
Given a platform-specific RADON model, the DECOMP_TOOL must be able to obtain an optimal deployment scheme that minimizes the operating costs on the target cloud platform under the performance requirements

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#4]
From D2.1 (Companion)
| ID | R-T3.2-4 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As an Operations Engineer, I want to optimize the deployment of an application on a particular cloud platform. |
| Requirement | Given a platform-specific RADON model, the DECOMP_TOOL must be able to obtain an optimal deployment scheme that minimizes the operating costs on the target cloud platform under the performance requirements. |
| Extended Description | The method assumes a platform-specific RADON model that comprises nodes and relationships that are dependent on a particular cloud platform. The requirement needs to encompass yearly costs. |
| Priority | Must have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by gcasale** [comment]
Approved change to include yearly costs.

**Comment by zhululai** [comment]
Deployment optimization for various AWS services has been supported by the decomposition tool.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
