### ISSUE TITLE
Given a deployable RADON model, the DECOMP_TOOL could be able to refine certain properties of the nodes and relationships using runtime monitoring data

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#5]
From D2.1 (Companion)
| ID | R-T3.2-5 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As an Operations Engineer, I want to enhance the accuracy of the description for an application. |
| Requirement | Given a deployable RADON model, the DECOMP_TOOL could be able to refine certain properties of the nodes and relationships using runtime monitoring data. |
| Extended Description | The refined properties may include arrival rates, numbers of users, think times, network latency and service times. |
| Priority | Could have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
Accuracy enhancement for AWS Lambda has been supported by the decomposition tool.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
