### ISSUE TITLE
The DECOMP_TOOL should be able to carry out architecture decomposition, deployment optimization and accuracy enhancement for a mixed-grained RADON model

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#6]
From D2.1 (Companion)
| ID | R-T3.2-6 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to add new features to a monolithic application as microservices or serverless functions. |
| Requirement | The DECOMP_TOOL should be able to carry out architecture decomposition, deployment optimization and accuracy enhancement for a mixed-grained RADON model. |
| Extended Description | A RADON application or model is said to be mixed-grained if it consists of a monolith, microservices or serverless functions with separate storages. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
All the three features have been supported by the decomposition tool. Although these features may only be applied to a limited range of mixed-grained cloud services, extensibility to other cloud services is preserved by their implementations.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
