### ISSUE TITLE
The DECOMP_TOOL should be able to carry out architecture decomposition, deployment optimization and accuracy enhancement for a RADON model with heterogeneous cloud technologies

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#7]
From D2.1 (Companion)
| ID | R-T3.2-7 |
| --- | --- | 
| Type | FUNCTIONAL_SUITABILITY |
| User Story | As a Software Designer, I want to integrate an application with heterogeneous cloud technologies. |
| Requirement | The DECOMP_TOOL should be able to carry out architecture decomposition, deployment optimization and accuracy enhancement for a RADON model with heterogeneous cloud technologies. |
| Extended Description | The supported technologies may include containers, virtual machines, object storages, block storages, databases, message queues, data streams and in-memory caches. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
All the three features have been supported by the decomposition tool. Although these features may only be applied to a limited range of heterogeneous cloud services, extensibility to other cloud services is preserved by their implementations.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Approved
