### ISSUE TITLE
The DECOMP_TOOL should be able to allow the option of specifying the granularity level for architecture decomposition and generate a grained RADON model at that level

### ISSUE THREAD

**Issue by zhululai** [radon-h2020/radon-decomposition-tool#9]
From D2.1 (Companion)
| ID | R-T3.2-9 |
| --- | --- | 
| Type | USABILITY |
| User Story | As an Operations Engineer, I want to decompose the architecture of an application at different granularity levels. |
| Requirement | The DECOMP_TOOL should be able to allow the option of specifying the granularity level for architecture decomposition and generate a grained RADON model at that level. |
| Extended Description | The available levels may include coarse-grained, fine-grained and mixed-grained. |
| Priority | Should have |
| Affected Tools | DECOMP_TOOL |
| Means of Verification | Code review, unit tests and use cases |
| Dependency | R-T4.2-1 to R-T4.2-3 |

**Comment by zhululai** [comment]
Architecture decomposition at various granularity levels have been supported by the decomposition tool. The decomposition granularity of each node can be specified through an optional property.

**Comment by zhululai** [comment]
@gcasale close requirement.

**Comment by gcasale** [comment]
Agreed
